# Generated by Django 3.0.7 on 2023-01-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0320_auto_20230119_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerextended',
            name='cust_StoreCard',
        ),
        migrations.RemoveField(
            model_name='customerextended',
            name='cust_img',
        ),
        migrations.RemoveField(
            model_name='customerextended',
            name='cust_phoneo',
        ),
        migrations.RemoveField(
            model_name='customerextended',
            name='cust_point_value',
        ),
        migrations.RemoveField(
            model_name='customerextended',
            name='phone4',
        ),
        migrations.RemoveField(
            model_name='treatmentpackage',
            name='treatmentids',
        ),
    ]
