# Generated by Django 3.0.7 on 2023-01-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0324_auto_20230120_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cust_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_conditioner',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_interest',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_pic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_prods',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_religion',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_salaryrange',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_shampoo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_stylist',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_stylistname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_vipdisc',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_vipdiscper',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dob_status',
        ),
    ]
