# Generated by Django 3.0.7 on 2023-01-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0326_auto_20230120_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='anniversary',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='corporatecust',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='create_logno',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_cardno',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_group',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_group2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_group3',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_linkcode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_pic_b',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_point',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dateofreg',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='iscorporate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modify_logno',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='product_group',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='referby',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='site_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='skin_type',
        ),
    ]
