# Generated by Django 3.0.7 on 2023-01-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0327_auto_20230120_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cardexpiry_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cb_cn',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cb_pp',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cb_trmt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='clonecustcode',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_agegroup',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_height',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_language',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_location',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_sn',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_weight',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='custclass_changedate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='externalvipprofile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='staff_service',
        ),
    ]
