# Generated by Django 3.0.7 on 2023-01-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0330_auto_20230120_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='site_code',
            field=models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True),
        ),
    ]
