# Generated by Django 3.0.7 on 2023-01-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0332_auto_20230123_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerextended',
            name='estimated_deliverydate',
        ),
        migrations.RemoveField(
            model_name='customerextended',
            name='is_pregnant',
        ),
        migrations.RemoveField(
            model_name='customerextended',
            name='no_of_children',
        ),
        migrations.RemoveField(
            model_name='customerextended',
            name='no_of_weeks_pregnant',
        ),
        migrations.AddField(
            model_name='customer',
            name='estimated_deliverydate',
            field=models.DateTimeField(blank=True, db_column='EstimatedDeliveryDate', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_pregnant',
            field=models.BooleanField(blank=True, db_column='IsPregnant', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_children',
            field=models.IntegerField(blank=True, db_column='NoOfChildren', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_weeks_pregnant',
            field=models.IntegerField(blank=True, db_column='NoOfWeeksOfPregnancy', null=True),
        ),
    ]
