# Generated by Django 3.0.7 on 2023-01-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0336_auto_20230124_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerextend',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgbackend',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgbilling',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgcatalog',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgcommission',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgcustomer',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgdayend',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flginventory',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flginvoices',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgkpidashboard',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgpo',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgproject',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgquantum',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgquotation',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgtcm',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='next_appt',
        ),
        migrations.RemoveField(
            model_name='treatmentaccount',
            name='lpackage',
        ),
        migrations.RemoveField(
            model_name='treatmentaccount',
            name='treat_code',
        ),
        migrations.AlterUniqueTogether(
            name='poshaud',
            unique_together={('sa_transacno', 'sa_custno', 'itemsite_code', 'sa_transacno_ref')},
        ),
        migrations.RemoveField(
            model_name='poshaud',
            name='cas_logno',
        ),
    ]
