# Generated by Django 3.0.7 on 2023-01-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0338_posdaud_holditemqty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fmspw',
            unique_together={('pw_userlogin',)},
        ),
    ]
