# Generated by Django 3.0.7 on 2023-02-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0340_displaycatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytable',
            name='paytypeimage',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
