# Generated by Django 3.0.7 on 2023-02-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0341_paytable_paytypeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayItem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('menu_code', models.CharField(db_column='menuCode', max_length=10)),
                ('stockid', models.IntegerField(blank=True, db_column='stockId', null=True)),
            ],
            options={
                'db_table': 'displayItem',
            },
        ),
    ]
