# Generated by Django 3.0.7 on 2023-02-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0342_displayitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='displayitem',
            unique_together={('menu_code', 'stockid')},
        ),
    ]
