# Generated by Django 3.0.7 on 2023-02-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0343_auto_20230210_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistaff',
            name='deposit',
            field=models.FloatField(db_column='Deposit', null=True),
        ),
    ]
