# Generated by Django 3.0.7 on 2023-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0345_multistaff_gt1deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treatmentcode',
            field=models.CharField(blank=True, db_column='treatmentCode', max_length=40, null=True),
        ),
    ]
