# Generated by Django 3.0.7 on 2023-02-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0346_appointment_treatmentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='duration',
            field=models.IntegerField(blank=True, db_column='Duration', null=True),
        ),
    ]
