# Generated by Django 3.0.7 on 2023-03-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0349_outletrequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletrequestlog',
            name='last_transaction_date',
            field=models.DateTimeField(blank=True, db_column='Last_Transaction_Date', null=True),
        ),
        migrations.AlterField(
            model_name='outletrequestlog',
            name='log_date',
            field=models.DateTimeField(blank=True, db_column='Log_Date', null=True),
        ),
    ]
