# Generated by Django 3.0.7 on 2023-03-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0350_auto_20230306_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletrequestlog',
            name='to_site',
        ),
        migrations.AddField(
            model_name='outletrequestlog',
            name='requesting_site',
            field=models.CharField(blank=True, db_column='Requesting_Site', max_length=200, null=True),
        ),
    ]
