# Generated by Django 3.0.7 on 2023-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0351_auto_20230307_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerextended',
            name='original_sitecode',
            field=models.CharField(blank=True, db_column='Original_SiteCode', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customerextended',
            unique_together={('cust_code',)},
        ),
    ]
