# Generated by Django 3.0.7 on 2023-04-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0128_auto_20230112_1401'),
        ('cl_table', '0353_auto_20230329_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidopencondition',
            name='itemcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart'),
        ),
    ]
