# Generated by Django 3.0.7 on 2023-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0354_prepaidopencondition_itemcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercondition',
            name='isactive',
            field=models.BooleanField(db_column='IsActive', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vouchercondition',
            name='line_no',
            field=models.IntegerField(blank=True, db_column='Line_No', null=True),
        ),
    ]
