# Generated by Django 3.0.7 on 2023-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0356_auto_20230420_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='conditiontype1',
            field=models.CharField(db_column='ConditionType1', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='conditiontype2',
            field=models.CharField(db_column='ConditionType2', max_length=500, null=True),
        ),
    ]
