# Generated by Django 3.0.7 on 2023-04-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0357_auto_20230420_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidaccountcondition',
            name='itembrand_id',
            field=models.IntegerField(blank=True, db_column='itembrand_id', null=True),
        ),
        migrations.AddField(
            model_name='prepaidaccountcondition',
            name='itemdept_id',
            field=models.IntegerField(blank=True, db_column='itemdept_id', null=True),
        ),
    ]
