# Generated by Django 3.0.7 on 2023-05-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0359_auto_20230424_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhelper',
            name='sa_date',
            field=models.DateTimeField(null=True),
        ),
    ]
