# Generated by Django 3.0.7 on 2023-05-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0360_auto_20230511_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='conditiontype1',
            field=models.CharField(db_column='ConditionType1', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='conditiontype2',
            field=models.CharField(db_column='ConditionType2', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='conditiontype1',
            field=models.CharField(db_column='ConditionType1', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='conditiontype2',
            field=models.CharField(db_column='ConditionType2', max_length=80, null=True),
        ),
    ]
