# Generated by Django 3.0.7 on 2023-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0364_prepaidaccount_terminate_prepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidaccount',
            name='terminate_prepaid',
            field=models.BooleanField(default=False),
        ),
    ]
