# Generated by Django 3.0.7 on 2023-06-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0366_auto_20230529_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdaud',
            name='dt_discdesc',
            field=models.CharField(blank=True, db_column='dt_discDesc', max_length=200, null=True),
        ),
    ]
