# Generated by Django 3.0.7 on 2023-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0368_auto_20230607_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_birthday',
            field=models.FloatField(blank=True, db_column='Cust_BirthDay', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_birthmonth',
            field=models.FloatField(blank=True, db_column='Cust_BirthMonth', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_birthyear',
            field=models.FloatField(blank=True, db_column='Cust_BirthYear', null=True),
        ),
    ]
