# Generated by Django 3.0.7 on 2023-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0369_auto_20230613_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custallowsendwhatsapp',
            field=models.BooleanField(db_column='custallowsendwhatsapp', default=False),
        ),
    ]
