# Generated by Django 3.0.7 on 2023-07-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0371_invoicetemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicetemplate',
            unique_together={('name',)},
        ),
    ]
