# Generated by Django 3.0.7 on 2023-07-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0375_taxtype2taxcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdaud',
            name='t2_tax_amt',
            field=models.FloatField(blank=True, db_column='T2_Tax_Amt', null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='t2_tax_code',
            field=models.CharField(blank=True, db_column='T2_Tax_Code', max_length=20, null=True),
        ),
    ]
