# Generated by Django 3.0.7 on 2023-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0376_auto_20230731_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempprepaidAccountCondition',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pp_no', models.CharField(blank=True, db_column='PP_NO', max_length=50, null=True)),
                ('pp_type', models.CharField(blank=True, db_column='PP_TYPE', max_length=50, null=True)),
                ('pp_desc', models.CharField(blank=True, db_column='PP_DESC', max_length=50, null=True)),
                ('p_itemtype', models.CharField(blank=True, db_column='P_ItemType', max_length=50, null=True)),
                ('item_code', models.CharField(blank=True, max_length=20, null=True)),
                ('conditiontype1', models.CharField(blank=True, db_column='ConditionType1', max_length=20, null=True)),
                ('conditiontype2', models.CharField(blank=True, db_column='ConditionType2', max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=4, max_digits=19, null=True)),
                ('rate', models.CharField(blank=True, db_column='Rate', max_length=20, null=True)),
                ('membercardnoaccess', models.BooleanField(db_column='MemberCardNoAccess')),
                ('use_amt', models.FloatField(blank=True, db_column='Use_Amt', null=True)),
                ('remain', models.FloatField(blank=True, db_column='Remain', null=True)),
                ('pos_daud_lineno', models.FloatField(blank=True, db_column='POS_Daud_LineNo', null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TempPrepaid_Account_Condition',
            },
        ),
    ]
