# Generated by Django 3.0.7 on 2023-08-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0378_tempprepaidaccountcondition_prepaidaccount_cond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempprepaidaccountcondition',
            name='membercardnoaccess',
            field=models.BooleanField(db_column='MemberCardNoAccess', null=True),
        ),
    ]
