# Generated by Django 3.0.7 on 2023-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0379_auto_20230811_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempprepaidaccountcondition',
            name='cart_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
