# Generated by Django 3.0.7 on 2023-08-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0133_remove_itemcart_prepaid_useamt'),
        ('cl_table', '0380_tempprepaidaccountcondition_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempcartprepaidAccCond',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cart_id', models.CharField(max_length=20, null=True)),
                ('use_amt', models.FloatField(blank=True, db_column='Use_Amt', null=True)),
                ('bal_amt', models.FloatField(blank=True, db_column='Bal_Amt', null=True)),
                ('itemcart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart')),
                ('prepaidaccount_cond', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PrepaidAccountCondition')),
            ],
            options={
                'db_table': 'TempCartPrepaid_Account_Condition',
            },
        ),
    ]
