# Generated by Django 3.0.7 on 2023-08-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0381_tempcartprepaidacccond'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempprepaidaccountcondition',
            name='prepaid_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PrepaidAccount'),
        ),
    ]
