# Generated by Django 3.0.7 on 2023-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0382_tempprepaidaccountcondition_prepaid_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcartprepaidacccond',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tempprepaidaccountcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
