# Generated by Django 3.0.7 on 2023-08-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0384_prepaidaccountcondition_topup_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidaccount',
            name='preacc_useid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
