# Generated by Django 3.0.7 on 2023-09-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0389_auto_20230914_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidaccount',
            name='lpackage',
            field=models.BooleanField(db_column='lPackage', null=True),
        ),
    ]
