# Generated by Django 3.0.7 on 2023-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0391_auto_20230915_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetup',
            name='isactive',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
