# Generated by Django 3.0.7 on 2023-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0392_auto_20230916_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='link_flag',
            field=models.BooleanField(db_column='Link Flag', default=False, null=True),
        ),
    ]
