# Generated by Django 3.0.7 on 2023-09-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0393_auto_20230919_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
