# Generated by Django 3.0.7 on 2023-10-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0394_customer_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetemplate',
            name='order_seq',
            field=models.IntegerField(blank=True, db_column='Order_Seq', null=True),
        ),
    ]
