# Generated by Django 3.0.7 on 2023-10-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0395_invoicetemplate_order_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembatchsno',
            name='itemcart',
            field=models.IntegerField(blank=True, db_column='itemcart', null=True),
        ),
    ]
