# Generated by Django 3.0.7 on 2023-11-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0396_itembatchsno_itemcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmspw',
            name='flgPoint',
            field=models.BooleanField(db_column='flgPoint', default=False),
        ),
    ]
