# Generated by Django 3.0.7 on 2023-12-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0398_apiurls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemContent',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('itemcode', models.CharField(blank=True, db_column='ITEM_CODE', max_length=30, null=True)),
                ('content_line_no', models.IntegerField(blank=True, db_column='Content_Line_No', null=True)),
                ('content_detail_1', models.CharField(blank=True, db_column='Content_Detail_1', max_length=200, null=True)),
                ('Content_Detail_2', models.CharField(blank=True, db_column='Content_Detail_2', max_length=200, null=True)),
                ('is_active', models.BooleanField(db_column='ISACTIVE', default=True)),
            ],
            options={
                'db_table': 'Item_Content',
            },
        ),
    ]
