# Generated by Django 3.0.7 on 2023-12-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0399_itemcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcontent',
            old_name='Content_Detail_2',
            new_name='Content_detail_2',
        ),
        migrations.AlterUniqueTogether(
            name='itemcontent',
            unique_together={('content_detail_1',)},
        ),
    ]
