# Generated by Django 3.0.7 on 2023-12-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0400_auto_20231219_2002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcontent',
            unique_together=set(),
        ),
    ]
