# Generated by Django 3.0.7 on 2023-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0401_auto_20231219_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptreatment',
            name='remarks',
            field=models.CharField(blank=True, db_column='Remarks', max_length=255, null=True),
        ),
    ]
