# Generated by Django 3.0.7 on 2023-12-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0402_tmptreatment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custclass_changedate',
            field=models.DateTimeField(blank=True, db_column='CustClass_ChangeDate', null=True),
        ),
    ]
