# Generated by Django 3.0.7 on 2023-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0072_remove_tmpitemhelpersession_treatmentpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsitelist',
            name='is_automember',
            field=models.BooleanField(db_column='IsAutoMember', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='itemsitelist',
            name='is_empvalidate',
            field=models.BooleanField(db_column='is_empvalidate', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemsitelist',
            name='is_nric',
            field=models.BooleanField(db_column='Nric', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='itemsitelist',
            name='service_sel',
            field=models.BooleanField(db_column='Service_Selection', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='itemsitelist',
            name='service_text',
            field=models.BooleanField(db_column='Service_Text', default=False, null=True),
        ),
    ]
