# Generated by Django 3.0.7 on 2023-10-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0074_auto_20230916_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpitemhelpersession',
            name='percent',
            field=models.FloatField(blank=True, db_column='Percent', null=True),
        ),
        migrations.AddField(
            model_name='tmpitemhelpersession',
            name='work_amt',
            field=models.FloatField(blank=True, db_column='Work_Amount', null=True),
        ),
    ]
