# Generated by Django 3.0.7 on 2023-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0075_auto_20231025_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentusage',
            name='item_desc',
            field=models.CharField(db_column='Item_Desc', max_length=250),
        ),
    ]
