# Generated by Django 3.0.7 on 2023-05-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0128_auto_20230112_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymodechangelog',
            name='taudid',
        ),
    ]
