# Generated by Django 3.0.7 on 2023-08-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0131_auto_20230722_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='prepaid_useamt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
