# Generated by Django 3.0.7 on 2023-08-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0132_itemcart_prepaid_useamt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcart',
            name='prepaid_useamt',
        ),
    ]
