# Generated by Django 3.0.7 on 2023-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0134_itemcart_prepaid_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrecord',
            name='isdiscount',
            field=models.BooleanField(db_column='isdiscount', default=False, null=True),
        ),
    ]
