# Generated by Django 3.0.7 on 2023-09-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0136_auto_20230924_1937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smtpsettings',
            unique_together={('email_subject', 'site_code')},
        ),
    ]
